kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-web-app-hardcoded
  namespace: default
  labels: 
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "willing-possum-demo-web-app",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /\r\n",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 8080,
            "bindAddr": "172.16.3.36"
          },
          "partition": "f5-bigip-ctlr",
          "balance": "least-connections-member",
          "mode": "http"
        }
      }
    }
